name: build

on:
  push:
    branches: [master]
  # pull_request:
  #   types: [closed]

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      #Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.20.1"

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        
      #Test
      - run: go test -v ./... -coverprofile="coverage.txt" -covermode=atomic

      #Upload codecov
      - run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}