name: pr-build

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Setup
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.20.1"

      #Test
      - run: go test -v ./... -coverprofile="coverage.txt" -covermode=atomic

      #Upload codecov
      - run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}